/*
  A synthetic sample of professional claim lines, in plain English instead of
  CPT codes (decision 2026-09-12: a non-clinical reviewer should follow the
  demo without a code lookup).

  Generated by a SEEDED pseudo-random function, never Math.random: the savings
  figure must be identical on every reload and every deploy. A demo number that
  drifts reads as broken. Patterns are planted so the preset rules fire.
*/

export const SERVICES = [
  'Office visit',
  'Physical therapy (15-min unit)',
  'MRI, lower back',
  'Flu shot',
  'Basic lab panel',
  'Telehealth check-in',
  'Emergency room visit',
  'Knee injection',
] as const
export const MODIFIERS = ['none', 'telehealth', 'bilateral', 'separate service'] as const
export const PLACES = ['office', 'hospital outpatient', 'telehealth', 'emergency'] as const
export const DIAGNOSES = ['back pain', 'flu', 'diabetes', 'knee injury', 'routine'] as const
export const SEXES = ['F', 'M'] as const

export type Service = (typeof SERVICES)[number]
export type Modifier = (typeof MODIFIERS)[number]
export type Place = (typeof PLACES)[number]
export type Diagnosis = (typeof DIAGNOSES)[number]
export type Sex = (typeof SEXES)[number]

export type ClaimLine = {
  id: string
  service: Service
  modifier: Modifier
  placeOfService: Place
  diagnosis: Diagnosis
  units: number
  memberAge: number
  memberSex: Sex
  billed: number
  paid: number
}

/** mulberry32 — a 10-line seeded PRNG. Deterministic across runs and hosts. */
function seeded(seed: number) {
  let a = seed >>> 0
  return () => {
    a = (a + 0x6d2b79f5) >>> 0
    let t = a
    t = Math.imul(t ^ (t >>> 15), t | 1)
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61)
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

/** Typical paid amount per unit, in dollars, by service. */
const UNIT_PAID: Record<Service, number> = {
  'Office visit': 95,
  'Physical therapy (15-min unit)': 32,
  'MRI, lower back': 640,
  'Flu shot': 28,
  'Basic lab panel': 45,
  'Telehealth check-in': 70,
  'Emergency room visit': 820,
  'Knee injection': 210,
}

const USUAL_PLACE: Record<Service, Place> = {
  'Office visit': 'office',
  'Physical therapy (15-min unit)': 'office',
  'MRI, lower back': 'hospital outpatient',
  'Flu shot': 'office',
  'Basic lab panel': 'office',
  'Telehealth check-in': 'telehealth',
  'Emergency room visit': 'emergency',
  'Knee injection': 'office',
}

const USUAL_DX: Record<Service, readonly Diagnosis[]> = {
  'Office visit': ['routine', 'diabetes', 'flu', 'back pain'],
  'Physical therapy (15-min unit)': ['back pain', 'knee injury'],
  'MRI, lower back': ['back pain'],
  'Flu shot': ['routine', 'flu'],
  'Basic lab panel': ['routine', 'diabetes'],
  'Telehealth check-in': ['routine', 'diabetes', 'flu'],
  'Emergency room visit': ['knee injury', 'flu', 'back pain'],
  'Knee injection': ['knee injury'],
}

function build(count: number, seed: number): ClaimLine[] {
  const rand = seeded(seed)
  const pick = <T>(list: readonly T[]) => list[Math.floor(rand() * list.length)]!
  const between = (lo: number, hi: number) => lo + Math.floor(rand() * (hi - lo + 1))

  // Weighted like a real panel: visits and therapy dominate, imaging and ER are rare.
  const WEIGHTED: readonly Service[] = [
    'Office visit',
    'Office visit',
    'Office visit',
    'Physical therapy (15-min unit)',
    'Physical therapy (15-min unit)',
    'Physical therapy (15-min unit)',
    'Telehealth check-in',
    'Telehealth check-in',
    'Basic lab panel',
    'Basic lab panel',
    'Flu shot',
    'MRI, lower back',
    'Emergency room visit',
    'Knee injection',
  ]

  return Array.from({ length: count }, (_, i) => {
    const service = pick(WEIGHTED)
    let units = 1
    let modifier: Modifier = 'none'
    let placeOfService = USUAL_PLACE[service]
    let diagnosis = pick(USUAL_DX[service])
    const r = rand()

    // Planted patterns — the mistakes an edit rule is meant to catch.
    if (service === 'Physical therapy (15-min unit)') {
      units = r < 0.35 ? between(5, 8) : between(1, 4) // some sessions over the 4-unit cap
    } else if (service === 'Telehealth check-in') {
      if (r < 0.35)
        placeOfService = 'office' // telehealth service, but billed as in-office
      else modifier = 'telehealth'
    } else if (service === 'MRI, lower back') {
      if (r < 0.25) diagnosis = 'routine' // imaging with no supporting diagnosis
    } else if (service === 'Knee injection') {
      if (r < 0.3) modifier = 'bilateral'
    } else if (service === 'Office visit') {
      if (r < 0.1) modifier = 'separate service'
    }

    const unitPaid = UNIT_PAID[service] * (0.85 + rand() * 0.3)
    const paid = Math.round(unitPaid * units)
    const billed = Math.round(paid * (1.3 + rand() * 0.6))

    return {
      id: `C-${String(1000 + i)}`,
      service,
      modifier,
      placeOfService,
      diagnosis,
      units,
      memberAge: between(2, 84),
      memberSex: pick(SEXES),
      billed,
      paid,
    }
  })
}

export const SAMPLE: readonly ClaimLine[] = build(150, 20260912)
